spring:
  profiles:
    active: jocke
---



spring:
  profiles: jocke
  data:
    mongodb:
      uri: mongodb+srv://user:userpassword@cluster0.pgrth.mongodb.net/fortuneteller?retryWrites=true&w=majority
server:
  port: 8084
---
---

spring:
  profiles: testuser
  data:
    mongodb:
      uri: mongodb://localhost/test
server:
  port: 8083

