spring:
  profiles:
    active: testuser
  port: 8082
---
spring:
  profiles: jocke
  data:
    mongodb:
      uri: mongodb+srv://user:userpassword@cluster0.pgrth.mongodb.net/fortuneteller?retryWrites=true&w=majority
  port: 8083
---
---
spring:
  profiles: testuser
  data:
    mongodb:
      uri: mongodb://localhost/test
  port: 8084


